<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>irobot_hand_description</name>
  <version>3.1.0</version>
  <description>
    This package contains iRobot hand description files.
    The files should yield identical model as the the one provided by
    iRobot under the name handle_description with a couple of changes:
    Currently, we are working on updating the inertia to be more realistic.
    The meshes have been post processed with regenerated face and vertex normals.
    Gazebo elements have been added for simulation needs.
  </description>
  <maintainer email="hsu@osrfoundation.org">John Hsu</maintainer>
  <license>Apache 2.0</license>
  <url type="website">http://gazebosim.org/wiki/DRC</url>
  <author email="hsu@osrfoundation.org">Brian Gerkey and John Hsu</author>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>xacro</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <test_depend>ament_cmake_pytest</test_depend>
  <test_depend>xacro</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
