<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>drcsim_gazebo_ros_plugins</name>
  <version>3.1.0</version>
  <description>The drcsim_gazebo_ros_plugins package</description>
  <maintainer email="hsu@osrfoundation.org">John Hsu</maintainer>
  <license>Apache 2.0</license>
  <url type="website">http://gazebosim.org/wiki/DRC</url>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>gz-sim8</depend>
  <depend>gz-plugin2</depend>
  <depend>gz-transport13</depend>
  <depend>gz-msgs10</depend>
  <depend>gz-common5</depend>
  <depend>gz-math7</depend>

  <depend>rclcpp</depend>
  <depend>atlas_msgs</depend>
  <depend>osrf_msgs</depend>
  <depend>sandia_hand_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>handle_msgs</depend>
  <depend>std_msgs</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
